# Generated by Django 5.0.6 on 2024-05-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_genre_options_alter_city_name_alter_venue_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name', '-created_on']},
        ),
    ]
