# Generated by Django 5.0.6 on 2024-06-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
