# Generated by Django 5.0.6 on 2024-06-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_details_alter_event_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
    ]
