# Generated by Django 5.0.6 on 2024-06-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_venue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
