# Generated by Django 5.0.6 on 2024-06-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_city_options_event_my_link_alter_event_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='my_link',
            field=models.URLField(blank=True, verbose_name='Add a Website'),
        ),
    ]
