# Generated by Django 5.0.6 on 2024-05-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_listing',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, "Let's Go!")], default=1),
        ),
        migrations.AlterField(
            model_name='event_listing',
            name='bio',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event_listing',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
